sudo: false
language: python
env:
  - DEBUG=True
branches:
  only:
    - master
python:
  - "2.7"
install:
  - pip install django
  - pip install -e git+https://github.com/political-memory/django-representatives.git@parltrack_in_representatives#egg=representatives
  - pip install -e .
  - wget https://github.com/political-memory/political_memory/archive/openshift.tar.gz
  - tar xvzf openshift.tar.gz
  - pip install -r political_memory-openshift/requirements.txt
  - mv test.db political_memory-openshift/db.sqlite
script:
  - political_memory-openshift/manage.py migrate
  - political_memory-openshift/manage.py import_parltrack_all_votes
